### PR TITLE
Replace viper with standard JSON decoding

### PR DESCRIPTION
**Pull request by glyn**
Fixes https://github.com/deislabs/duffle/issues/817

### CODE REVIEW

**Comment by carolynvs** [comment]
Viper is still being imported in `cmd/duffle/install.go`. Once you remove that import, you should be able to run `dep ensure` and see it disappear from Gopkg.lock.

**Comment by glyn** [comment]
> Viper is still being imported in `cmd/duffle/install.go`. Once you remove that import, you should be able to run `dep ensure` and see it disappear from Gopkg.lock.

Thanks @carolynvs - that does seem to clean up the dependency...

However, `parseValues` in `cmd/duffle/install.go` depends rather deeply on viper and will need more thought to reword as standard JSON decoding. Any insights into the design of that code would be helpful.

**Comment by carolynvs** [comment]
Here's the original implementation of `parseValues` with just the relevant json part. The function  used to do a switch on the file extension (*.json, *.toml, etc) which we don't need anymore:

```
vals := map[string]interface{}{}
data, err := ioutil.ReadFile(file)
if err != nil {
  return vals, err
}
err = json.Unmarshal(data, &vals)
return vals, err
```

**Comment by glyn** [comment]
> Here's the original implementation of `parseValues` with just the relevant json part.

Thanks @carolynvs - I just found that in git history, but thanks for the confirmation this is still the right approach.

**Pull request merged**
