### PR TITLE
Move to deislabs/cnab-go

### PR DESCRIPTION
**Pull request by silvin-lubecki**
Vendor and use github.com/deislabs/cnab-go library, which extracted pkg/bundle.

Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
@radu-matei I don't have access to the duffle-CI logs, so I don't know what is failling...

**Comment by radu-matei** [comment]
@silvin-lubecki -- I was planning this as part of #681, but I don't really see any reason not to have this as a separate PR.

Let me see why the Brigade build didn't kick in, and I'll update here.

Thanks!

**Comment by silvin-lubecki** [comment]
Just rebased and fixed the imports, thank you @radu-matei 👍

**Comment by radu-matei** [comment]
GitHub seems to be having some troubles today, both CIs are currently pending:

```
&{Response:0xc000114000 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 Rate:github.Rate{Limit:6100, Remaining:6059, Reset:github.Timestamp{2019-04-11 17:25:49 +0000 UTC}}}Error: POST https://api.github.com/repos/deislabs/duffle/check-runs: 500  [] (got )
```

**Comment by radu-matei** [comment]
GitHub seems to be having some troubles today, both CIs are currently pending:

```
&{Response:0xc000114000 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 Rate:github.Rate{Limit:6100, Remaining:6059, Reset:github.Timestamp{2019-04-11 17:25:49 +0000 UTC}}}Error: POST https://api.github.com/repos/deislabs/duffle/check-runs: 500  [] (got )
```

**Comment by radu-matei** [comment]
GitHub seems to be having some troubles today, both CIs are currently pending:

```
&{Response:0xc000114000 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 Rate:github.Rate{Limit:6100, Remaining:6059, Reset:github.Timestamp{2019-04-11 17:25:49 +0000 UTC}}}Error: POST https://api.github.com/repos/deislabs/duffle/check-runs: 500  [] (got )
```

**Comment by radu-matei** [comment]
Any particular reason why `deislabs/cnab-go` is not pinpointed in `Gopkg.toml`?

**Comment by silvin-lubecki** [comment]
Well, the `gopkg.lock` already pin-points the `deislabs/cnab-go` package, so I guess it won't change unless someone does an explicit update on it, or if the resolver needs bump it because of a transitive dependency.

 I think the less you have in the `Gopkg.toml` the better, and you should only pin-point hard requirements. In an ideal world you even should have nothing in this file, as `dep` automatically resolves all the dependencies and transitive ones.

That said, I may be wrong and would be happy to add it to the `Gopkg.toml` file 👍

**Pull request merged**
