### PR TITLE
Remove tar file representation of images in thick bundles

### PR DESCRIPTION
**Pull request by glyn**
Fixes https://github.com/deislabs/duffle/issues/767

### CODE REVIEW

**Comment by glyn** [comment]
The CI failure was due to https://github.com/goreleaser/godownloader/issues/118. Someone is working on this...

**Comment by silvin-lubecki** [comment]
This PR needs a rebase

**Comment by silvin-lubecki** [comment]
Nevermind, it seems there's a new button "Update Branch" on github 👍

**Comment by technosophos** [comment]
This went red on the merge PR because of #773

**Comment by jeremyrickard** [comment]
This is good after the master fix @technosophos @glyn @silvin-lubecki, I'll be merging it now.

**Pull request merged**
