### PR TITLE
Use Go 1.12 for docker builds

### PR DESCRIPTION
**Pull request by glyn**
An alternative would be to bump quay.io/deis/lightweight-docker-go to use a
later version of Go, but it's probably safer to get out of that game and use
the more widely supported golang image instead.

Fixes https://github.com/deislabs/duffle/issues/773

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
@glyn I think there's an issue with the vendoring test. Is there any reason why you had to bump kubernetes dependencies ?

**Comment by glyn** [comment]
> @glyn I think there's an issue with the vendoring test. Is there any reason why you had to bump kubernetes dependencies ?

The vendoring test does `dep check` and so I issued `dep ensure` thinking this was supposed to ensure the vendored code matches `Gopkg.lock`.

**Comment by silvin-lubecki** [comment]
@glyn would it be possible to split this PR in 2? One to move to `golang:1.12` image, and the other to bump the dependencies? Or at least in 2 separated commits? It's hard to see why this bump was needed 🤔

**Comment by glyn** [comment]
> @glyn would it be possible to split this PR in 2? One to move to `golang:1.12` image, and the other to bump the dependencies? Or at least in 2 separated commits?

I've split it into two commits. I don't think I could get CI to pass without both commits.

> It's hard to see why this bump was needed 🤔

Try running `SKIP_DOCKER=true make verify-vendored-code` at master. I'd settle for another way of making this check pass if you'd like to suggest one. :-)

**Comment by carolynvs** [comment]
Let me take a look at what's up with our makefile / dep testing code because my gut says that we shouldn't have to bump dependencies for this.

**Comment by carolynvs** [comment]
@glyn The build for master is broken and isn't running on each push to master (but it is still triggering for PRs which is why you are getting hit with these problems). I am fixing master now and have @vdice getting the CI build running again. Once we are done, then you'll be able to rebase and just have the proper changes in your PR again.

**Comment by glyn** [comment]
> @glyn The build for master is broken and isn't running on each push to master (but it is still triggering for PRs which is why you are getting hit with these problems). I am fixing master now and have @vdice getting the CI build running again. Once we are done, then you'll be able to rebase and just have the proper changes in your PR again.

Thanks @carolynvs. I'm a little puzzled though. The sole purpose of this PR is to fix the build. I'll look forward to comparing your PR...

**Comment by glyn** [comment]
> @glyn The build for master is broken and isn't running on each push to master (but it is still triggering for PRs which is why you are getting hit with these problems). I am fixing master now and have @vdice getting the CI build running again. Once we are done, then you'll be able to rebase and just have the proper changes in your PR again.

Thanks @carolynvs. I'm a little puzzled though. The sole purpose of this PR is to fix the build. I'll look forward to comparing your PR...

**Comment by glyn** [comment]
> Let me take a look at what's up with our makefile / dep testing code because my gut says that we shouldn't have to bump dependencies for this.

I suspect the problem is that the two commits 4dccb95f1e14ac5367434ae86d8484c27f0182d2 and bf4df3a274b5e55b75bdf67e647b4271e0c8beb9 conflicted logically, but not in a way that git would detect, so the PR for the second commit didn't have its checked re-run after the first commit was merged.

**Comment by technosophos** [comment]
It took me a while to realize that this is actually a fix for broken master, not just a switch to Go 1.12.  So now I guess we have two PRs that are trying to fix #773. I don't actually have a strong preference for one or the other.

**Comment by jeremyrickard** [comment]
Hey @glyn there was some chat in the slack channel and the consensus was to merge #775 to fix the build. Can you rebase this to just handle the upgrade to 1.12? That's a more involved change (i.e. consumers will also need to bump to 1.12).

**Comment by glyn** [comment]
> Hey @glyn there was some chat in the slack channel and the consensus was to merge #775 to fix the build. Can you rebase this to just handle the upgrade to 1.12? That's a more involved change (i.e. consumers will also need to bump to 1.12).

I'll look into it. Actually, the only consumers who will be affected are those who specify `SKIP_DOCKER=true` when building, and they should know what they are doing.

Closing in favour of https://github.com/deislabs/duffle/pull/777 which has a more appropriate branch name.

**Pull request closed without merging**
